services:
  mongo:
    image: mongo:latest
    container_name: mongo_db
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo-data:/data/db

  user-service:
    build: .
    container_name: user_service
    restart: always
    depends_on:
      - mongo
    ports:
      - "5000:5000"
    env_file:
      - .env # Load environment variables from the .env file
    volumes:
      - .:/app
      - /app/node_modules
    command: [ "npm", "run", "dev" ]

volumes:
  mongo-data:
